### ISSUE TITLE
Port this extension to Firefox

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/CarbonFootprintGoogleMaps#6]
The port should be done in a way that both versions (Chrome and Firefox) share as much code as possible, in order to facilitate maintenance.

**Comment by heychirag** [comment]
I have submitted a proposal demonstrating steps to port this extension to both the browsers (Firefox and Safari) while simultaneously making it possible that all the three extension share as much code as possible. I would also be interested in implementing my own ideas that I have proposed, which I think will make the extension more accurate. Nevertheless, I would love to port this extension to other browsers as well (like Opera) so that this feature can be used by more and more people.
